# SITE CONFIGURATION
title: Open Neuroscience # your site title
author: amchagas # You :P
description: > # Meta description of Homepage
  Open Source projects for neuroscience
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://open-neuroscience.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Open Neuroscience
  links:
    - https://twitter.com/openeuroscience
    - https://www.facebook.com/OpenNeuroscience/
    #- https://www.linkedin.com/in/BenBalter
    #- https://plus.google.com/+BenBalter
    - https://github.com/open-neuroscience
    #- https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Hardware', link: '/hardware'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/about/contact'}

tagline: >
  Repository for Open Source Neuroscience projects!

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: openeuroscience@gmail.com # email for form submission

twitter_username: openeuroscience # replace with your_twitter_username or comment to remove link from footer
github_username:  amchagas # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

#disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  #- sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
